### PR TITLE
INancyEngine now implements IDisposable 

### LINKED ISSUE #1864: INancyEngine should be disposable and be disposed when the boostrapper and container is disposed.
Main problem [is here](https://github.com/NancyFx/Nancy/blob/master/src/Nancy/Owin/NancyMiddleware.cs#L98). When the middleware ( -> boostrapper -> container) is disposed, Nancy is still handling requests. Sometimes successfully. 

`INancyEngine` should be `IDisposable` and [here](https://github.com/NancyFx/Nancy/blob/master/src/Nancy/Owin/NancyMiddleware.cs#L98) should be seeing an ObjectDisposedException.

### PR DESCRIPTION
**Pull request by damianh**
It will no longer handle subsequent requests and will attempt to cooperatively cancel existing in-flight requests. Fixes #1864.

### CODE REVIEW

File: src/Nancy/NancyEngine.cs [hunk 1]
```diff
@@ -19,7 +19,7 @@
     /// <summary>
     /// Default engine for handling Nancy <see cref="Request"/>s.
     /// </summary>
-    public class NancyEngine : INancyEngine
+    public sealed class NancyEngine : INancyEngine
```
Comment (damianh) [inline src/Nancy/NancyEngine.cs]: Either `sealed` or fully implement the dispose pattern? Unless designed for inheritance, I'm on the side of 'sealed'.

**Comment by damianh** [comment]
Took slightly different track than reported in the issue - if after the engine is disposed, instead of throwing an `ObjectDisposedException`, the Task is immediately cancelled. Caller tend to treat cancelled tasks differently that other exception types. 

I think this is cleaner and matches what would happen when a request is cancelled under other terms also.

File: src/Nancy/NancyEngine.cs [hunk 2]
```diff
@@ -93,6 +95,10 @@ public class NancyEngine : INancyEngine
 
         public Task<NancyContext> HandleRequest(Request request, Func<NancyContext, NancyContext> preRequest, CancellationToken cancellationToken)
         {
+            var cts = CancellationTokenSource.CreateLinkedTokenSource(this.engineDisposedCts.Token, cancellationToken);
+
+            cts.Token.ThrowIfCancellationRequested();
```
Comment (damianh) [inline src/Nancy/NancyEngine.cs]: POI

File: src/Nancy/NancyEngineExtensions.cs [hunk 3]
```diff
@@ -66,8 +66,6 @@ public static NancyContext HandleRequest(this INancyEngine nancyEngine, Request
             nancyEngine
                 .HandleRequest(request, preRequest, cancellationToken)
                 .WhenCompleted(t => onComplete(t.Result), t => onError(t.Exception));
-
-            //this.HandleRequest(request, null, onComplete, onError);
```
Comment (damianh) [inline src/Nancy/NancyEngineExtensions.cs]: Removed commented out line...
