### PR TITLE
Removed GetAwaiter on Response

### LINKED ISSUE #2518: Why is Response awaitable?
### Prerequisites
- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of Nancy
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/NancyFx/Nancy/issues) and [closed](https://github.com/NancyFx/Nancy/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported
### Description

Why is Response awaitable?
### Steps to Reproduce

There was some noob confusion when having a method to return a response. `Get("/logout", async _ => await this.Logout(_));`

I determined that the method should return `Task<dynamic>` not `Task` but I think this was due to some confusion with intellisense saying that Response was awaitable eg `await Response.AsRedirect("/")` where in fact I should `return Response.AsRedirect("/")`

I assume Response is awaitable for rendering Views but what would that look like `return await View["Home"]` ??

Anyway just thought I'd log the issue for other noobs like me
### System Configuration

- Nancy version:
- Nancy host
  - [ ] ASP.NET
  - [ ] OWIN
  - [ ] Self-Hosted
  - [x] Other: Kestrel
- Other Nancy packages and versions: 2.0.0-barneyrubble
- Environment (Operating system, version and so on): Windows/OSX
- .NET Framework version: netcore
- Additional information:

### PR DESCRIPTION
**Pull request by thecodejunkie**
### Prerequisites

- [X] I have written a descriptive pull-request title
- [X] I have verified that there are no overlapping [pull-requests](https://github.com/NancyFx/Nancy/pulls) open
- [X] I have verified that I am following the Nancy [code style guidelines](https://github.com/NancyFx/Nancy/blob/45238076ad0b7f6ecabd6bae8469e30458d02efe/CONTRIBUTING.md#style-guidelines)
- [X] I have provided test coverage for my change (where applicable)

### Description
Removed the `GetAwaiter` method on `Response`. It was accidentally included when we added the new route syntax. 

Closes #2518

### CODE REVIEW

File: src/Nancy/Response.cs [hunk 1]
```diff
@@ -36,14 +36,14 @@ public Response()
...
 
-        /// <summary>
-        /// Gets the awaiter.
-        /// </summary>
-        /// <returns><see cref="TaskAwaiter{Response}"/></returns>
-        public TaskAwaiter<Response> GetAwaiter()
-        {
-            return Task.FromResult(this).GetAwaiter();
-        }
+        ///// <summary>
```
Comment (khellang) [inline src/Nancy/Response.cs]: Can we just remove it altogether, unless we plan to reintroduce it?

Comment (thecodejunkie) [inline src/Nancy/Response.cs]: Oh shit. Commented it out to test and then forgot to delete it. Will fix and update the PR :+1:

**Comment by thecodejunkie** [comment]
@khellang pushed
